/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactInfo = IDL.Record({
  'hours' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const MenuItem = IDL.Record({
  'name' : IDL.Text,
  'price' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addAdmin' : IDL.Func([IDL.Principal], [], []),
  'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
  'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'updateContactInfo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateMenuItem' : IDL.Func([IDL.Text, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactInfo = IDL.Record({
    'hours' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const MenuItem = IDL.Record({ 'name' : IDL.Text, 'price' : IDL.Float64 });
  
  return IDL.Service({
    'addAdmin' : IDL.Func([IDL.Principal], [], []),
    'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
    'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'updateContactInfo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateMenuItem' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };